### PR TITLE
added thin footer with links

### PR DESCRIPTION
**Pull request by zhukovdigital**
added thin footer

### CODE REVIEW

**Review by HankC138 — APPROVED** [review]
Concise and simple looks good 👍

**Comment by jsonin** [comment]
Why does the footer not show on most screens, even when there is plenty of "room"?
image

**Comment by jsonin** [comment]
Let's adjust the footer design.
Left align all text, so it aligns with "My StaffPlan" button and the screen title (like "People").

Text: 
Copyright © 2025 GoInvo. All rights reserved.   [SPACE] Privacy Policy and Terms of Use [link to  | Feedback [emailto link to staffplan@goinvo.com]

**Comment by ericbenwa** [comment]
A visual for Juhan's feedback.
Also revised his text some to include `Open Source` which will link to https://github.com/goinvo/staffplan-next-app
Which means we can remove Open Source from the dropdown in the top right of the navbar.

footer-footz

**Pull request merged**
