### PR TITLE
decoded avatarURL to prevent buggy profile pictures

### PR DESCRIPTION
**Pull request by HankC138**
this should prevent buggy avatar display when some avatars are encoded from the backend

### CODE REVIEW

**Review by zhukovdigital — APPROVED** [review]

**Comment by zhukovdigital** [comment]
looks good

**Comment by fermion** [comment]
@HankC138 did this fix the avatar issue for you locally? I'm still seeing the encoded URI being requested.

I also just noticed that this request is going to `https://ui.staffplan.com/_next/image?` which presumably is hitting Vercel? We may need to add something on the server side of next.js to handle this if we want to use these components?

**Comment by HankC138** [comment]
> @HankC138 did this fix the avatar issue for you locally? I'm still seeing the encoded URI being requested.
> 
> I also just noticed that this request is going to `https://ui.staffplan.com/_next/image?` which presumably is hitting Vercel? We may need to add something on the server side of next.js to handle this if we want to use these components?

I was unable to recreate the situation locally. all my profile images just worked so I was hoping this would solve it based on your initial issue.

**Comment by fermion** [comment]
@HankC138 gotcha, I'm somehow not surprised that this behaves fundamentally differently in each environment. Looking at the `Image` [class docs](https://nextjs.org/docs/pages/api-reference/components/image#src), I bet we need to add the root of these avatar URLs [to the `remotePatterns`](https://nextjs.org/docs/pages/api-reference/components/image#remotepatterns) so it's trusted?

**Comment by fermion** [comment]
Something like

```js
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'www.staffplan.com',
        port: '',
        pathname: '/rails/active_storage/**',
        search: '*',
      },
    ],
```
might work?

**Pull request merged**
